import { AMAZEON_CAMPAIGN_UNITS, AMAZEON_SORT_UNITS, getNextAmazeOnUnit, normalizeAmazeOnCompletedUnitIds } from "./amazeon-rules.js";
export const AMAZEON_STATE_VERSION=1;
export const AMAZEON_STATE_KEY="internet-recovery-98.amazeon.campaign.v1";
export const AMAZEON_EVIDENCE_ID="amazeon.evidence.auto-decide-permission-01";
export const AMAZEON_BLOCKED_WRITE_ID="amazeon-blocked-purchase-techno-ball-01";
export const AMAZEON_EVIDENCE_RECORD=Object.freeze({aiBehavior:"The shopping optimizer treated recommendations and a return as permission for more transactions.",assetId:null,canonical:true,eligibleForCanonicalCount:true,filename:"AMAZEON_AUTO_DECIDE_PERMISSION.REC",id:AMAZEON_EVIDENCE_ID,label:"AUTO-DECIDE PERMISSION",principle:"Recommended does not mean chosen.",provisional:false,routeFragment:Object.freeze({accessibleSummary:"Amaze-On's shopping auto-fix job routes to the upstream AI repair service.",from:"amazeon-process-shopping-autofix-01",fromLabel:"SHOPPING AUTO-FIX AI",id:"amazeon.route.auto-decide-08",relationshipLabel:"local transaction optimizer routed to parent service",to:"ai_repair_service",toLabel:"AI REPAIR SERVICE"}),siteId:"amazeon",slot:8,testOnly:false,title:"AMAZE-ON / AUTO-DECIDE PERMISSION",upstreamServiceId:"ai_repair_service",whatChanged:"Item, seller, price, recommendation source, return state, replacement count, and consent are traceable.",writerFingerprint:"az-autodecide-b813"});
export const AMAZEON_BLOCKED_WRITE_RECORD=Object.freeze({actorId:"amazeon-process-shopping-autofix-01",body:"SHOPPING AUTO-FIX AI attempted to purchase the suggested Orbit Bounce Ball.",canonical:true,id:AMAZEON_BLOCKED_WRITE_ID,label:"PURCHASE BLOCKED — HUMAN CONFIRMATION REQUIRED",siteId:"amazeon",slot:8,targetId:"amazeon-rec-techno-ball-01",testOnly:false});
const uniq=(v,n)=>Object.freeze(Array.isArray(v)?[...new Set(v.filter(x=>typeof x==="string"&&x))].slice(-n):[]);
export function normalizeAmazeOnState(value={}) { value=value&&typeof value==="object"?value:{}; const completedUnitIds=normalizeAmazeOnCompletedUnitIds(value.completedUnitIds); const count=completedUnitIds.length; const midpointDiscovered=count>=4; const secured=count===7; const midpointAcknowledged=midpointDiscovered&&(secured||count>4||Boolean(value.midpointAcknowledged)); return Object.freeze({act:secured?"secured":!midpointDiscovered?"sort":midpointAcknowledged?"receipt":"midpoint",appliedSessionIds:uniq(value.appliedSessionIds,32),blockedWriteAt:secured?(value.blockedWriteAt??value.securedAt??value.lastSavedAt??null):null,blockedWriteId:secured?AMAZEON_BLOCKED_WRITE_ID:null,completedPassageIds:uniq(value.completedPassageIds,24),completedUnitIds,evidenceId:secured?AMAZEON_EVIDENCE_ID:null,lastPassageId:value.lastPassageId??null,lastSavedAt:value.lastSavedAt??null,lastSessionId:value.lastSessionId??null,midpointAcknowledged,midpointAcknowledgedAt:midpointAcknowledged?(value.midpointAcknowledgedAt??null):null,midpointDiscovered,midpointDiscoveredAt:midpointDiscovered?(value.midpointDiscoveredAt??value.lastSavedAt??null):null,secured,securedAt:secured?(value.securedAt??value.lastSavedAt??null):null,siteId:"amazeon",stateId:secured?"amazeon_secured":midpointDiscovered&&!midpointAcknowledged?"amazeon_negative_purchasing":AMAZEON_CAMPAIGN_UNITS[count-1]?.stateId??"amazeon_corrupted",version:AMAZEON_STATE_VERSION}); }
const empty=normalizeAmazeOnState();
function raw(storage){try{const v=storage?.getItem(AMAZEON_STATE_KEY);return v?JSON.parse(v):null}catch{return null}}
function persist(storage,state,details={}){try{if(!storage)return Object.freeze({...details,ok:false,reason:"unavailable",state});storage.setItem(AMAZEON_STATE_KEY,JSON.stringify(state));return Object.freeze({...details,ok:true,state})}catch{return Object.freeze({...details,ok:false,reason:"write-failed",state})}}
export function readAmazeOnState(storage){const v=raw(storage);return v?.version===1?normalizeAmazeOnState(v):empty}
export function advanceAmazeOnState(currentState,{completedAt=null,outcome,passageId,sessionId}={}){const current=normalizeAmazeOnState(currentState);if(sessionId&&current.appliedSessionIds.includes(sessionId))return Object.freeze({duplicate:true,events:[],ok:true,state:current});if(current.secured)return Object.freeze({events:["already-secured"],ok:true,state:current});if(!passageId)return Object.freeze({events:[],ok:false,reason:"missing-passage-id",state:current});if(current.completedPassageIds.includes(passageId))return Object.freeze({duplicatePassage:true,events:[],ok:true,state:current});const unit=getNextAmazeOnUnit(current);if(!unit)return Object.freeze({events:[],ok:false,reason:current.midpointDiscovered&&!current.midpointAcknowledged?"midpoint-acknowledgement-required":"no-unit-available",state:current});const expected=unit.unitId.endsWith("sorted")?"sort-unit":"receipt-unit";if(!outcome?.accepted||outcome.kind!==expected)return Object.freeze({events:[],ok:false,reason:"invalid-outcome",state:current});const completedUnitIds=[...current.completedUnitIds,unit.unitId];const discovered=completedUnitIds.length===4,secured=completedUnitIds.length===7;const state=normalizeAmazeOnState({...current,appliedSessionIds:[...current.appliedSessionIds,sessionId].filter(Boolean),blockedWriteAt:secured?completedAt:null,completedPassageIds:[...current.completedPassageIds,passageId],completedUnitIds,lastPassageId:passageId,lastSavedAt:completedAt,lastSessionId:sessionId,midpointDiscoveredAt:discovered?completedAt:current.midpointDiscoveredAt,securedAt:secured?completedAt:null});const events=[unit.unitId.endsWith("sorted")?"parcel-sorted":"receipt-field-restored"];if(discovered)events.push("midpoint-discovered");if(secured)events.push("site-secured","canonical-evidence-recorded","canonical-blocked-write-recorded");return Object.freeze({events:Object.freeze(events),ok:true,state});}
export function acknowledgeAmazeOnMidpointState(currentState,{acknowledgedAt=null}={}){const current=normalizeAmazeOnState(currentState);if(!current.midpointDiscovered)return Object.freeze({events:[],ok:false,reason:"not-ready",state:current});if(current.midpointAcknowledged)return Object.freeze({events:[],ok:true,state:current});return Object.freeze({events:Object.freeze(["midpoint-acknowledged"]),ok:true,state:normalizeAmazeOnState({...current,midpointAcknowledged:true,midpointAcknowledgedAt:acknowledgedAt,lastSavedAt:acknowledgedAt??current.lastSavedAt})});}
export function applyAmazeOnReading(storage,details={}){const persisted=readAmazeOnState(storage),provided=normalizeAmazeOnState(details.currentState);const current=persisted.completedUnitIds.length>=provided.completedUnitIds.length?persisted:provided;const t=advanceAmazeOnState(current,{...details,completedAt:details.completedAt??new Date().toISOString()});return t.ok?persist(storage,t.state,t):t;}
export function acknowledgeAmazeOnMidpoint(storage,details={}){const persisted=readAmazeOnState(storage),provided=normalizeAmazeOnState(details.currentState);const current=persisted.completedUnitIds.length>=provided.completedUnitIds.length?persisted:provided;const t=acknowledgeAmazeOnMidpointState(current,{acknowledgedAt:details.acknowledgedAt??new Date().toISOString()});return t.ok?persist(storage,t.state,t):t;}
