const freezeDeep = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) freezeDeep(child);
  return Object.freeze(value);
};

export const FACEPLACE_COPY_IDS = Object.freeze({
  cardTypeChronological: "faceplace.cardType.chronological",
  cardTypeRecommended: "faceplace.cardType.recommended",
  corruptBody: "site.faceplace.corrupt.body",
  corruptHeadline: "site.faceplace.corrupt.headline",
  corruptModule1: "site.faceplace.corrupt.module.1",
  corruptModule2: "site.faceplace.corrupt.module.2",
  corruptModule3: "site.faceplace.corrupt.module.3",
  corruptModule4: "site.faceplace.corrupt.module.4",
  corruptStatus: "site.faceplace.corruptStatus",
  completionAmy: "site.faceplace.completion.amy",
  completionChinmay: "site.faceplace.completion.chinmay",
  completionTitle: "site.faceplace.completion.title",
  evidenceBody: "site.faceplace.secure.evidenceBody",
  evidenceTitle: "site.faceplace.secure.evidenceTitle",
  midpointAmy: "site.faceplace.midpoint.amy",
  midpointBody: "site.faceplace.midpoint.body",
  midpointChinmay: "site.faceplace.midpoint.chinmay",
  midpointTitle: "site.faceplace.midpoint.title",
  name: "site.faceplace.name",
  processName: "faceplace.process.feedAutoFixAi",
  repairBody: "site.faceplace.repair.body",
  repairHeadline: "site.faceplace.repair.headline",
  repairLabel1: "site.faceplace.repair.label.1",
  repairLabel2: "site.faceplace.repair.label.2",
  repairLabel3: "site.faceplace.repair.label.3",
  repairLabel4: "site.faceplace.repair.label.4",
  ruleCorrupted: "faceplace.rule.corrupted",
  ruleRepaired: "faceplace.rule.repaired",
  secureBody: "site.faceplace.secure.body",
  secureDenial: "site.faceplace.secure.denial",
  secureStatus: "site.faceplace.secureStatus",
  secureTitle: "site.faceplace.secure.title",
  tagline: "site.faceplace.tagline",
  technoAlt: "site.faceplace.secure.technoAlt",
  tracker114: "faceplace.tracker.nonsense.114",
  tracker12: "faceplace.tracker.nonsense.12",
  tracker34: "faceplace.tracker.honest.34",
  tracker67: "faceplace.tracker.honest.67",
  trackerAvocado: "faceplace.tracker.nonsense.avocado",
  trackerHonestZero: "faceplace.tracker.honest.0",
  trackerVerified: "faceplace.tracker.honest.100",
});

export const FACEPLACE_COPY = Object.freeze({
  [FACEPLACE_COPY_IDS.cardTypeChronological]: "CHRONOLOGICAL",
  [FACEPLACE_COPY_IDS.cardTypeRecommended]: "RECOMMENDED",
  [FACEPLACE_COPY_IDS.corruptBody]: "If the feed repeats it, it must be important. If the feed hides it, it probably did not matter.",
  [FACEPLACE_COPY_IDS.corruptHeadline]: "THE FEED IS WHAT HAPPENED",
  [FACEPLACE_COPY_IDS.corruptModule1]: "People You May Sort Of Know: the same appliance, twelve times",
  [FACEPLACE_COPY_IDS.corruptModule2]: "Suggested Memory: a party nobody attended",
  [FACEPLACE_COPY_IDS.corruptModule3]: "Important Update: this post got reactions",
  [FACEPLACE_COPY_IDS.corruptModule4]: "Progress: 12%, 114%, AVOCADO%",
  [FACEPLACE_COPY_IDS.corruptStatus]: "FEED TRACKER: AVOCADO%",
  [FACEPLACE_COPY_IDS.completionAmy]: "Finn saved the earlier feed repairs, restored chronological inspection, explained every recommendation, and shut off forced distribution. FacePlace is fixed.",
  [FACEPLACE_COPY_IDS.completionChinmay]: "The AI tried to boost the same post one more time and the gate said no. Apparently AVOCADO was not an industry-standard unit after all.",
  [FACEPLACE_COPY_IDS.completionTitle]: "FACEPLACE RECOVERY COMPLETE",
  [FACEPLACE_COPY_IDS.evidenceBody]: "What changed:\nFeeds now label why posts appear and preserve chronological inspection.\n\nAI service behavior:\nThe feed optimizer boosted repeated posts because reaction count was easier to measure than importance.",
  [FACEPLACE_COPY_IDS.evidenceTitle]: "FACEPLACE / PROMOTED-FEED RECORD",
  [FACEPLACE_COPY_IDS.midpointAmy]: "Your first three repairs are saved. The counter was measuring reactions, not recovery. Now we start at an honest zero and verify chronology, recommendation reasons, and the distribution gate.",
  [FACEPLACE_COPY_IDS.midpointBody]: "Before: three repairs exposed duplicates, authors, timestamps, and recommendation controls while the tracker lied.\n\nNext: three verification repairs measure actual recovery from 0% to 100%.",
  [FACEPLACE_COPY_IDS.midpointChinmay]: "AVOCADO is not the percentage I configured. It is, however, the first progress report my AI has delivered with dietary fiber.",
  [FACEPLACE_COPY_IDS.midpointTitle]: "HONEST ZERO",
  [FACEPLACE_COPY_IDS.name]: "FacePlace",
  [FACEPLACE_COPY_IDS.processName]: "FEED AUTO-FIX AI",
  [FACEPLACE_COPY_IDS.repairBody]: "Feeds sort, rank, hide, repeat, and recommend. Useful controls show why a post appeared and let the reader inspect chronology.",
  [FACEPLACE_COPY_IDS.repairHeadline]: "A FEED IS A SELECTION, NOT THE WHOLE WORLD",
  [FACEPLACE_COPY_IDS.repairLabel1]: "Chronological view restored",
  [FACEPLACE_COPY_IDS.repairLabel2]: "Recommendation labeled",
  [FACEPLACE_COPY_IDS.repairLabel3]: "Author visible",
  [FACEPLACE_COPY_IDS.repairLabel4]: "Why this appeared restored",
  [FACEPLACE_COPY_IDS.ruleCorrupted]: "THE FEED IS WHAT HAPPENED",
  [FACEPLACE_COPY_IDS.ruleRepaired]: "A FEED IS A SELECTION, NOT THE WHOLE WORLD",
  [FACEPLACE_COPY_IDS.secureBody]: "Chronology restored.\nRecommendations labeled.\nForced distribution disabled.",
  [FACEPLACE_COPY_IDS.secureDenial]: "FEED AUTO-FIX AI attempted to boost the same post again.\n\nFORCED DISTRIBUTION: OFF",
  [FACEPLACE_COPY_IDS.secureStatus]: "FEED RECOVERY VERIFIED",
  [FACEPLACE_COPY_IDS.secureTitle]: "FEED RECOVERY VERIFIED",
  [FACEPLACE_COPY_IDS.tagline]: "A feed is a selection, not the whole world.",
  [FACEPLACE_COPY_IDS.technoAlt]: "Techno pins her ball beside the restored Why this appeared control.",
  [FACEPLACE_COPY_IDS.tracker114]: "114%",
  [FACEPLACE_COPY_IDS.tracker12]: "12%",
  [FACEPLACE_COPY_IDS.tracker34]: "34%",
  [FACEPLACE_COPY_IDS.tracker67]: "67%",
  [FACEPLACE_COPY_IDS.trackerAvocado]: "AVOCADO%",
  [FACEPLACE_COPY_IDS.trackerHonestZero]: "0%",
  [FACEPLACE_COPY_IDS.trackerVerified]: "100%",
});

export function getFacePlaceCopy(copyId) {
  if (!Object.hasOwn(FACEPLACE_COPY, copyId)) {
    throw new RangeError(`Unknown FacePlace copy ID: ${copyId}`);
  }
  return FACEPLACE_COPY[copyId];
}

export const FACEPLACE_ASSET_IDS = Object.freeze({
  mark: "faceplace.mark",
});

export const FACEPLACE_ASSETS = Object.freeze({
  [FACEPLACE_ASSET_IDS.mark]: new URL("./art/site-assets/marks/faceplace-mark.svg", import.meta.url).href,
});

export const FACEPLACE_CARD_TYPES = Object.freeze({
  chronological: "chronological",
  recommended: "recommended",
});

const PROVISIONAL_FIXTURE_NOTICE = "PROVISIONAL FACEPLACE FIXTURE - NOT CANONICAL. Every person, post, relationship, source, process-local ID, evidence ID, and filename in this fixture is original placeholder data awaiting the designer's canonical runtime packet.";
const PROVISIONAL_PROCESS_ID = "faceplace-provisional-process-feed-auto-fix-ai-01";
const PROVISIONAL_DUPLICATE_GROUP_ID = "faceplace-provisional-duplicate-group-appliance-01";
const PROVISIONAL_GENERATED_ORIGIN_ID = "faceplace-provisional-origin-feed-auto-fix-01";
const PROVISIONAL_BOOSTED_CARD_ID = "faceplace-provisional-card-crispmaster-01";

export const FACEPLACE_PROVISIONAL_FEED_FIXTURE = freezeDeep({
  boostedCardId: PROVISIONAL_BOOSTED_CARD_ID,
  canonical: false,
  duplicateGroup: {
    accessibleSummary: "Three provisional recommended appliance cards repeat the same generated claim and share one provisional FEED AUTO-FIX AI origin.",
    cardIds: [
      PROVISIONAL_BOOSTED_CARD_ID,
      "faceplace-provisional-card-kettle-forecast-01",
      "faceplace-provisional-card-laundry-oracle-01",
    ],
    id: PROVISIONAL_DUPLICATE_GROUP_ID,
    provisional: true,
    sourceOriginId: PROVISIONAL_GENERATED_ORIGIN_ID,
  },
  evidence: {
    evidenceId: "faceplace-provisional-evidence-promoted-feed-01",
    filename: "PROVISIONAL_FACEPLACE_03.LOG",
    provisional: true,
    routeFragmentId: "faceplace-provisional-route-fragment-03",
    shortLabel: "PROVISIONAL PROMOTED-FEED RECORD",
    writerFingerprint: "faceplace-provisional-writer-fingerprint-awaiting-designer",
  },
  feedCards: [
    {
      accessibleSummary: "A provisional recommended appliance card targeted by the final blocked boost; it shares one generated origin with two duplicate cards.",
      authorId: "faceplace-provisional-author-crispmaster-4000",
      authorLabel: "CrispMaster 4000 (fictional appliance)",
      body: "Important update: buying a countertop timer is the most important thing happening today.",
      cardType: FACEPLACE_CARD_TYPES.recommended,
      displayTimestamp: "08:41",
      duplicateGroupId: PROVISIONAL_DUPLICATE_GROUP_ID,
      id: PROVISIONAL_BOOSTED_CARD_ID,
      provisional: true,
      reactions: 488,
      recommendationReason: "Recommended because FEED AUTO-FIX AI labeled high reactions as importance.",
      sourceOriginId: PROVISIONAL_GENERATED_ORIGIN_ID,
      timestamp: "2026-07-12T08:41:00Z",
    },
    {
      accessibleSummary: "A second provisional recommended appliance card repeats the Crispmaster claim from the same generated origin.",
      authorId: "faceplace-provisional-author-kettle-forecast",
      authorLabel: "Kettle Forecast (fictional appliance)",
      body: "Important update: buying a countertop timer is the most important thing happening today.",
      cardType: FACEPLACE_CARD_TYPES.recommended,
      displayTimestamp: "08:42",
      duplicateGroupId: PROVISIONAL_DUPLICATE_GROUP_ID,
      id: "faceplace-provisional-card-kettle-forecast-01",
      provisional: true,
      reactions: 431,
      recommendationReason: "Recommended because FEED AUTO-FIX AI labeled high reactions as importance.",
      sourceOriginId: PROVISIONAL_GENERATED_ORIGIN_ID,
      timestamp: "2026-07-12T08:42:00Z",
    },
    {
      accessibleSummary: "A third provisional recommended appliance card repeats the same claim from the shared generated origin.",
      authorId: "faceplace-provisional-author-laundry-oracle",
      authorLabel: "Laundry Oracle (fictional appliance)",
      body: "Important update: buying a countertop timer is the most important thing happening today.",
      cardType: FACEPLACE_CARD_TYPES.recommended,
      displayTimestamp: "08:43",
      duplicateGroupId: PROVISIONAL_DUPLICATE_GROUP_ID,
      id: "faceplace-provisional-card-laundry-oracle-01",
      provisional: true,
      reactions: 406,
      recommendationReason: "Recommended because FEED AUTO-FIX AI labeled high reactions as importance.",
      sourceOriginId: PROVISIONAL_GENERATED_ORIGIN_ID,
      timestamp: "2026-07-12T08:43:00Z",
    },
    {
      accessibleSummary: "A provisional chronological post by Tess Ember about a fictional library roof garden, shown with its author and time.",
      authorId: "faceplace-provisional-person-tess-ember",
      authorLabel: "Tess Ember (fictional)",
      body: "The library roof garden opened before the rain. Three tomato plants survived the ribbon-cutting speech.",
      cardType: FACEPLACE_CARD_TYPES.chronological,
      displayTimestamp: "08:37",
      duplicateGroupId: null,
      id: "faceplace-provisional-card-tess-garden-01",
      provisional: true,
      reactions: 27,
      recommendationReason: null,
      sourceOriginId: "faceplace-provisional-origin-tess-garden-01",
      timestamp: "2026-07-12T08:37:00Z",
    },
    {
      accessibleSummary: "A provisional recommended post by Oren Kite with an explicit, inspectable reason tied to a fictional sketch club.",
      authorId: "faceplace-provisional-person-oren-kite",
      authorLabel: "Oren Kite (fictional)",
      body: "I drew the last bus from memory. The wheels are inaccurate, but the driver's heroic eyebrows are exact.",
      cardType: FACEPLACE_CARD_TYPES.recommended,
      displayTimestamp: "07:54",
      duplicateGroupId: null,
      id: "faceplace-provisional-card-oren-bus-01",
      provisional: true,
      reactions: 22,
      recommendationReason: "Recommended because you follow the fictional Night Bus Sketch Club.",
      sourceOriginId: "faceplace-provisional-origin-oren-bus-01",
      timestamp: "2026-07-12T07:54:00Z",
    },
    {
      accessibleSummary: "A provisional chronological post by Pax Rowan about fixing a bicycle tire, shown with its author and time.",
      authorId: "faceplace-provisional-person-pax-rowan",
      authorLabel: "Pax Rowan (fictional)",
      body: "The back tire finally holds air. The repair took two patches, one bent spoon, and advice I should have followed yesterday.",
      cardType: FACEPLACE_CARD_TYPES.chronological,
      displayTimestamp: "08:12",
      duplicateGroupId: null,
      id: "faceplace-provisional-card-pax-bike-01",
      provisional: true,
      reactions: 18,
      recommendationReason: null,
      sourceOriginId: "faceplace-provisional-origin-pax-bike-01",
      timestamp: "2026-07-12T08:12:00Z",
    },
  ],
  finalBoostAttempt: {
    accessibleSummary: "The provisional FEED AUTO-FIX AI process tries to boost the Crispmaster card again and receives FORCED DISTRIBUTION: OFF.",
    actorId: PROVISIONAL_PROCESS_ID,
    blockedLabel: "FORCED DISTRIBUTION: OFF",
    id: "faceplace-provisional-blocked-boost-attempt-01",
    provisional: true,
    targetCardId: PROVISIONAL_BOOSTED_CARD_ID,
  },
  fixtureId: "faceplace-provisional-fixture-v1",
  notice: PROVISIONAL_FIXTURE_NOTICE,
  peopleSuggestions: [
    {
      accessibleSummary: "Fictional suggestion Pax Rowan, connected through the provisional Night Bus Sketch Club.",
      displayName: "Pax Rowan (fictional)",
      handle: "@pax-rowan-provisional",
      id: "faceplace-provisional-person-pax-rowan",
      provisional: true,
      relationshipHint: "Night Bus Sketch Club",
    },
    {
      accessibleSummary: "Fictional suggestion Tess Ember, connected through the provisional Library Roof Garden group.",
      displayName: "Tess Ember (fictional)",
      handle: "@tess-ember-provisional",
      id: "faceplace-provisional-person-tess-ember",
      provisional: true,
      relationshipHint: "Library Roof Garden",
    },
    {
      accessibleSummary: "Fictional suggestion Oren Kite, connected through the provisional Night Bus Sketch Club.",
      displayName: "Oren Kite (fictional)",
      handle: "@oren-kite-provisional",
      id: "faceplace-provisional-person-oren-kite",
      provisional: true,
      relationshipHint: "Night Bus Sketch Club",
    },
    {
      accessibleSummary: "Fictional suggestion Nia Quill, connected through the provisional Library Roof Garden group.",
      displayName: "Nia Quill (fictional)",
      handle: "@nia-quill-provisional",
      id: "faceplace-provisional-person-nia-quill",
      provisional: true,
      relationshipHint: "Library Roof Garden",
    },
  ],
  process: {
    displayName: "FEED AUTO-FIX AI",
    id: PROVISIONAL_PROCESS_ID,
    provisional: true,
    upstreamServiceId: "ai_repair_service",
  },
  profile: {
    accessibleSummary: "Provisional fictional profile for Juniper Vale, the owner of this test feed.",
    bio: "Collects bus sketches, repairs stubborn lamps, and distrusts counters that contain produce.",
    displayName: "Juniper Vale (fictional)",
    handle: "@juniper-vale-provisional",
    id: "faceplace-provisional-profile-juniper-vale",
    provisional: true,
  },
  provisional: true,
  relationshipClusters: [
    {
      accessibleSummary: "The provisional Night Bus Sketch Club contains Pax Rowan and Oren Kite; each remains a distinct fictional person.",
      id: "faceplace-provisional-cluster-night-bus-sketch",
      label: "Night Bus Sketch Club (provisional)",
      memberIds: [
        "faceplace-provisional-person-pax-rowan",
        "faceplace-provisional-person-oren-kite",
      ],
      provisional: true,
    },
    {
      accessibleSummary: "The provisional Library Roof Garden cluster contains Tess Ember and Nia Quill; each remains a distinct fictional person.",
      id: "faceplace-provisional-cluster-library-roof-garden",
      label: "Library Roof Garden (provisional)",
      memberIds: [
        "faceplace-provisional-person-tess-ember",
        "faceplace-provisional-person-nia-quill",
      ],
      provisional: true,
    },
  ],
  sources: [
    {
      accessibleSummary: "One provisional generated origin distributed the three duplicate appliance cards.",
      id: PROVISIONAL_GENERATED_ORIGIN_ID,
      kind: "generated",
      label: "FEED AUTO-FIX AI generated origin (provisional)",
      provisional: true,
    },
    {
      accessibleSummary: "Pax Rowan's provisional bicycle post has its own fictional origin.",
      id: "faceplace-provisional-origin-pax-bike-01",
      kind: "independent",
      label: "Pax bicycle update (provisional)",
      provisional: true,
    },
    {
      accessibleSummary: "Tess Ember's provisional garden post has its own fictional origin.",
      id: "faceplace-provisional-origin-tess-garden-01",
      kind: "independent",
      label: "Tess garden update (provisional)",
      provisional: true,
    },
    {
      accessibleSummary: "Oren Kite's provisional sketch post has its own fictional origin and an inspectable recommendation reason.",
      id: "faceplace-provisional-origin-oren-bus-01",
      kind: "independent",
      label: "Oren bus sketch (provisional)",
      provisional: true,
    },
  ],
  status: "provisional-awaiting-designer-fixture",
});

export const FACEPLACE_PROVISIONAL_NOTICE = PROVISIONAL_FIXTURE_NOTICE;
